import type { BlockDef, CallerTypeDef } from './types';

export const CALLER_TYPES: CallerTypeDef[] = [
  { id: 'donor',    label: 'Donor',     desc: 'Restaurant, grocer, individual giving food', icon: 'box' },
  { id: 'foodbank', label: 'Food Bank', desc: 'Verified org distributing to recipients',    icon: 'truck' },
  { id: 'receiver', label: 'Receiver',  desc: 'Household requesting food assistance',       icon: 'person' },
];

export const BLOCKS: BlockDef[] = [
  { id: 'caller',    title: 'Caller Identification', subtitle: 'identify_caller',           icon: 'person',
    fields: ['phone', 'status', 'matched_record'] },
  { id: 'user',      title: 'User Profile',          subtitle: 'register_new_user',         icon: 'id',
    fields: ['user_id', 'phone', 'zip_code', 'household_size', 'language', 'created_at'] },
  { id: 'nearby',    title: 'Nearby Food Banks',     subtitle: 'get_nearby_food_banks',     icon: 'pin',
    fields: ['search_zip', 'results'], listField: 'results' },
  { id: 'available', title: 'Available Food',        subtitle: 'get_available_food',        icon: 'box',
    fields: ['search_zip', 'income_tier', 'listings'], listField: 'listings' },
  { id: 'claim',     title: 'Food Claim',            subtitle: 'claim_food_listing',        icon: 'check',
    fields: ['listing_id', 'food_type', 'pickup_hint', 'phone', 'hold_expires'] },
  { id: 'request',   title: 'Pickup Request',        subtitle: 'request_food_from_food_bank', icon: 'truck',
    fields: ['request_id', 'recipient_phone', 'listing_id', 'food_bank', 'food_bank_phone', 'pickup_window', 'sms_confirmation'] },
];

export const SAMPLE_META = {
  callId: 'CALL-2A8F-3091',
  startedAt: '2026-05-10T14:32:08-07:00',
  agent: 'Alex · MESA',
  callerNumber: '+1 (510) 555-0142',
  totalDuration: 98,
  channel: 'Inbound · Voice',
  intent: 'Find available food',
  language: 'English',
  region: 'Berkeley, CA',
};

export const SAMPLE_TIMELINE = [
  { t: 0, kind: 'turn' as const, speaker: 'agent' as const,
    text: "Hi there, you've reached MESA — the food assistance line. To get started, can I confirm the phone number you're calling from?" },
  { t: 7.5, kind: 'turn' as const, speaker: 'caller' as const,
    text: "Yeah, it's five-one-zero, five-five-five, zero-one-four-two." },
  { t: 12, kind: 'tool' as const, name: 'identify_caller',
    args: { phone: '+15105550142' }, result: { found: false, message: 'No matching record' },
    durationMs: 240, writes: [
      { block: 'caller', field: 'phone', value: '+1 (510) 555-0142' },
      { block: 'caller', field: 'status', value: 'New caller' },
      { block: 'caller', field: 'matched_record', value: '—' },
    ] },
  { t: 13.4, kind: 'classify' as const, callerType: 'receiver', confidence: 0.94,
    rationale: 'Caller asked for food assistance for their family — matches Receiver path.',
    writes: [{ block: 'type', field: 'caller_type', value: 'receiver' }] },
  { t: 14, kind: 'turn' as const, speaker: 'agent' as const,
    text: "Thanks. Looks like you're new to MESA — I'd love to get you set up. What zip code are you in?" },
  { t: 20, kind: 'turn' as const, speaker: 'caller' as const, text: 'Nine-four-seven-zero-three.' },
  { t: 22.5, kind: 'turn' as const, speaker: 'agent' as const, text: 'Great. And how many people are in your household?' },
  { t: 26, kind: 'turn' as const, speaker: 'caller' as const, text: 'Four — me, my husband, and two kids.' },
  { t: 30, kind: 'turn' as const, speaker: 'agent' as const, text: 'Got it. What language do you prefer for follow-ups?' },
  { t: 33, kind: 'turn' as const, speaker: 'caller' as const, text: 'English is fine, thank you.' },
  { t: 35.5, kind: 'tool' as const, name: 'register_new_user',
    args: { phone: '+15105550142', zip_code: '94703', household_size: 4, lang: 'en' },
    result: { user_id: 'U-77214', created: true }, durationMs: 410, writes: [
      { block: 'user', field: 'user_id', value: 'U-77214' },
      { block: 'user', field: 'phone', value: '+1 (510) 555-0142' },
      { block: 'user', field: 'zip_code', value: '94703' },
      { block: 'user', field: 'household_size', value: '4' },
      { block: 'user', field: 'language', value: 'en' },
      { block: 'user', field: 'created_at', value: '2026-05-10 14:32:43' },
    ] },
  { t: 38, kind: 'turn' as const, speaker: 'agent' as const, text: "You're all set. Let me pull up the food banks closest to you." },
  { t: 41.5, kind: 'tool' as const, name: 'get_nearby_food_banks',
    args: { zip: '94703' }, result: { count: 3 }, durationMs: 320, writes: [
      { block: 'nearby', field: 'search_zip', value: '94703' },
      { block: 'nearby', field: 'results', value: [
        { name: 'Berkeley Food Pantry', address: '1600 Sacramento St', distance_mi: 0.6, phone: '+15105505555' },
        { name: 'Alameda County Community Food Bank', address: '7900 Edgewater Dr, Oakland', distance_mi: 4.2, phone: '+15106352465' },
        { name: 'Dorothy Day House', address: '2362 Bancroft Way', distance_mi: 1.1, phone: '+15105484728' },
      ] },
    ] },
  { t: 44.5, kind: 'turn' as const, speaker: 'agent' as const,
    text: "I found three within five miles — the closest is Berkeley Food Pantry on Sacramento Street. Let me see what's actually available for pickup right now." },
  { t: 52, kind: 'tool' as const, name: 'get_available_food',
    args: { zip: '94703', income_tier: 'qualifying' }, result: { count: 5 }, durationMs: 510, writes: [
      { block: 'available', field: 'search_zip', value: '94703' },
      { block: 'available', field: 'income_tier', value: 'qualifying' },
      { block: 'available', field: 'listings', value: [
        { id: 'L-3041', food_type: 'Fresh produce', quantity: '≈ 20 lbs', donor: "Trader Joe's · 4th St", pickup_until: 'Today 8:00 PM' },
        { id: 'L-3042', food_type: 'Boxed salads', quantity: '15 units', donor: 'Sweetgreen · Shattuck', pickup_until: 'Today 7:00 PM' },
        { id: 'L-3043', food_type: 'Bakery bread', quantity: '≈ 12 loaves', donor: 'Acme Bread', pickup_until: 'Today 9:00 PM' },
        { id: 'L-3044', food_type: 'Dairy', quantity: '8 gal milk', donor: 'Berkeley Bowl', pickup_until: 'Tomorrow 10:00 AM' },
        { id: 'L-3045', food_type: 'Prepared meals', quantity: '20 portions', donor: 'Cheese Board', pickup_until: 'Today 9:30 PM' },
      ] },
    ] },
  { t: 56, kind: 'turn' as const, speaker: 'agent' as const,
    text: "I have a few things — Trader Joe's just dropped off about twenty pounds of fresh produce, and Sweetgreen has fifteen boxed salads available until seven tonight. Anything sound good?" },
  { t: 67, kind: 'turn' as const, speaker: 'caller' as const, text: 'The produce would be amazing — my kids love fruit.' },
  { t: 71, kind: 'tool' as const, name: 'claim_food_listing',
    args: { food_type: 'fresh produce', pickup_hint: 'trader joes 4th st', phone: '+15105550142' },
    result: { listing_id: 'L-3041', held: true }, durationMs: 380, writes: [
      { block: 'claim', field: 'listing_id', value: 'L-3041' },
      { block: 'claim', field: 'food_type', value: 'Fresh produce' },
      { block: 'claim', field: 'pickup_hint', value: 'trader joes 4th st' },
      { block: 'claim', field: 'phone', value: '+1 (510) 555-0142' },
      { block: 'claim', field: 'hold_expires', value: 'Today 7:30 PM' },
    ] },
  { t: 75, kind: 'turn' as const, speaker: 'agent' as const,
    text: "I've got that on hold for you. Pickup will be at Berkeley Food Pantry — they'll have it ready. Want me to send a confirmation text?" },
  { t: 83, kind: 'turn' as const, speaker: 'caller' as const, text: 'Yes please.' },
  { t: 85, kind: 'tool' as const, name: 'request_food_from_food_bank',
    args: { recipient_phone: '+15105550142', listing_id: 'L-3041', food_bank_phone: '+15105505555' },
    result: { request_id: 'R-88621', sms_sent: true }, durationMs: 460, writes: [
      { block: 'request', field: 'request_id', value: 'R-88621' },
      { block: 'request', field: 'recipient_phone', value: '+1 (510) 555-0142' },
      { block: 'request', field: 'listing_id', value: 'L-3041' },
      { block: 'request', field: 'food_bank', value: 'Berkeley Food Pantry' },
      { block: 'request', field: 'food_bank_phone', value: '+1 (510) 550-5555' },
      { block: 'request', field: 'pickup_window', value: 'Today 4:00 – 7:30 PM' },
      { block: 'request', field: 'sms_confirmation', value: 'Sent ✓' },
    ] },
  { t: 90, kind: 'turn' as const, speaker: 'agent' as const,
    text: "All set. You'll get a text in a moment with the address and pickup window. Anything else I can help with?" },
  { t: 95, kind: 'turn' as const, speaker: 'caller' as const, text: "That's it — thank you so much." },
  { t: 97, kind: 'turn' as const, speaker: 'agent' as const, text: "You're welcome. Take care." },
];
